# Generated by Django 5.0.2 on 2024-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
