# Generated by Django 5.0.2 on 2024-03-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_header', models.CharField(max_length=100)),
                ('introduction_body', models.CharField(max_length=1000)),
            ],
        ),
    ]
