# Generated by Django 5.0.2 on 2024-03-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_number_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='message.number'),
        ),
    ]
