# Generated by Django 5.0.2 on 2024-03-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
