# Generated by Django 5.0.2 on 2024-03-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='country_flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='number_images/'),
        ),
    ]
